import { useMemo, useState } from 'react'
import type { PracticeMode, PracticeSession, VocabularyBank } from './types'
import { createPracticeSession, extendPracticeSession, restorePracticeQuestions, selectPracticeQuestions, selectRandomQuestions, selectReviewQuestions, selectUnseenQuestions } from './practice'
import { summarizeQuestions } from './statistics'
import { clearQuizcardAttempts, clearQuizcardSession, loadQuizcardAttempts, loadQuizcardSession, quizcardQuestions, quizcardSubjectId, saveQuizcardAttempt, saveQuizcardSession } from './quizcard-practice'

export function AdaptiveQuizcardStudy({ subjectId, vocabulary, onBack, onAwardXp }: { subjectId: string; vocabulary: VocabularyBank; onBack: () => void; onAwardXp: (amount: 1 | 2) => void }) {
  const storeId = quizcardSubjectId(subjectId); const questions = useMemo(() => quizcardQuestions(storeId, vocabulary.entries), [storeId, vocabulary.entries]); const entries = useMemo(() => new Map(vocabulary.entries.map(entry => [`quizcard-${entry.vocabularyId}`, entry])), [vocabulary.entries])
  const [session, setSession] = useState<PracticeSession | null>(() => loadQuizcardSession(storeId)); const [position, setPosition] = useState(0); const [flipped, setFlipped] = useState(false); const [result, setResult] = useState<boolean | null>(null); const [view, setView] = useState<'modes' | 'cards' | 'statistics'>('modes')
  const active = session ? restorePracticeQuestions(session, questions) ?? [] : []; const question = active[position]; const card = question ? entries.get(question.id) : null
  const start = (nextMode: PracticeMode) => { const attempts = loadQuizcardAttempts(storeId); const picked = nextMode === 'smart' ? selectPracticeQuestions(questions, attempts) : nextMode === 'random' ? selectRandomQuestions(questions) : nextMode === 'unseen' ? selectUnseenQuestions(questions, attempts) : selectReviewQuestions(questions, attempts); if (!picked.length) return; const next = createPracticeSession(storeId, nextMode, picked); setSession(next); saveQuizcardSession(next); setPosition(0); setFlipped(false); setResult(null); setView('cards') }
  const resume = () => { if (!session || !active.length) { clearQuizcardSession(storeId); setSession(null); return } setPosition(session.position); setFlipped(session.isLocked); setResult(session.isLocked ? session.selectedOptionIds[0] === 'remembered' : null); setView('cards') }
  const review = (remembered: boolean) => { if (!session || !question || result !== null) return; const next = { ...session, selectedOptionIds: [remembered ? 'remembered' : 'not-remembered'], isLocked: true, correctCount: session.correctCount + Number(remembered), updatedAt: new Date().toISOString() }; setSession(next); saveQuizcardSession(next); saveQuizcardAttempt(storeId, { questionId: question.id, questionVersion: 1, selectedOptionId: next.selectedOptionIds[0], isCorrect: remembered, answeredAt: new Date().toISOString() }); onAwardXp(remembered ? 2 : 1); setResult(remembered) }
  const next = () => { if (!session) return; let current = session; if (position + 1 >= active.length) { const extended = extendPracticeSession(session, questions, loadQuizcardAttempts(storeId)); if (extended.questionRefs.length <= session.questionRefs.length) return; current = extended; setSession(extended); saveQuizcardSession(extended) } const updated = { ...current, position: position + 1, selectedOptionIds: [], isLocked: false, updatedAt: new Date().toISOString() }; setSession(updated); saveQuizcardSession(updated); setPosition(updated.position); setFlipped(false); setResult(null) }
  if (view === 'statistics') { const summary = summarizeQuestions(questions, loadQuizcardAttempts(storeId)); const statuses = [['not_practiced', 'Chưa xem'], ['learning', 'Đang học'], ['weak', 'Hay quên'], ['developing', 'Đang nhớ'], ['stable', 'Ổn'], ['mastered', 'Nhớ tốt']] as const; return <main className="japanese-study-shell"><header className="japanese-study-header"><button className="text-button inline-button" type="button" onClick={onBack}>← Quay lại từ vựng</button><p className="eyebrow">JPD123 · Quizcard</p><h1>Thống kê Quizcard</h1><p>{summary.totalAttempts} lần tự đánh giá · Tỷ lệ nhớ {summary.accuracy}%.</p></header><section className="vocabulary-panel"><div className="statistics-list">{statuses.map(([status, label]) => <div className="statistics-card" key={status}><strong>{label}</strong><small>{summary.counts[status]} từ</small></div>)}</div><button className="danger-button" type="button" onClick={() => { clearQuizcardAttempts(storeId); setView('modes') }}>Xóa thống kê Quizcard</button><button className="text-button" type="button" onClick={() => setView('modes')}>Quay lại</button></section></main> }
  if (view === 'cards' && card) return <main className="japanese-study-shell"><header className="practice-header"><span>JPD123 · Quizcard thông minh</span><span>Đã xem: {position}</span><button className="text-button inline-button" type="button" onClick={() => { clearQuizcardSession(storeId); setSession(null); setView('statistics') }}>Kết thúc & xem Statistics</button></header><section className="quizcard-panel" aria-live="polite"><article className={flipped ? 'quizcard flipped' : 'quizcard'}><p className="quizcard-label">{flipped ? 'Phiên âm và nghĩa' : 'Tiếng Nhật'}</p><h2 lang="ja">{flipped ? card.kana : card.written}</h2>{flipped && <><p className="quizcard-romaji">{card.romaji}</p><p className="quizcard-meaning">{card.meaningVi}</p></>}</article>{!flipped && <button className="primary-button" type="button" onClick={() => setFlipped(true)}>Lật thẻ</button>}{flipped && result === null && <div className="quizcard-actions"><button className="text-button inline-button quizcard-back-button" type="button" onClick={() => setFlipped(false)}>← Xem lại tiếng Nhật</button><button className="primary-button" type="button" onClick={() => review(true)}>Tôi nhớ đúng · +2 XP</button><button className="secondary-button" type="button" onClick={() => review(false)}>Tôi chưa nhớ · +1 XP</button></div>}{result !== null && <><p className="quizcard-reward">{result ? 'Đã nhớ · +2 XP' : 'Chưa nhớ · +1 XP'}.</p><button className="primary-button" type="button" onClick={next}>Thẻ tiếp theo →</button></>}</section></main>
  return <main className="japanese-study-shell"><header className="japanese-study-header"><button className="text-button inline-button" type="button" onClick={onBack}>← Quay lại từ vựng</button><p className="eyebrow">JPD123 · Quizcard</p><h1>Học thẻ từ vựng thông minh</h1><p>Nhớ/chưa nhớ được lưu riêng và dùng để ưu tiên thẻ cần ôn. Bạn có thể học liên tục.</p></header><section className="vocabulary-panel"><div className="mode-list"><button type="button" onClick={() => start('smart')}><strong>Luyện thông minh</strong><span>Ưu tiên thẻ bạn hay quên.</span></button><button type="button" onClick={() => start('random')}><strong>Ngẫu nhiên toàn bộ</strong><span>Học liên tục, không lặp 20 thẻ gần nhất.</span></button><button type="button" onClick={() => start('unseen')}><strong>Chỉ thẻ chưa xem</strong><span>Chỉ lấy từ chưa từng tự đánh giá.</span></button><button type="button" onClick={() => start('review')}><strong>Thẻ cần ôn lại</strong><span>Từ đã xem và tỷ lệ nhớ từ 50% trở xuống.</span></button></div>{session && <button className="secondary-button" type="button" onClick={resume}>Tiếp tục lượt đang học</button>}<button className="text-button" type="button" onClick={() => setView('statistics')}>Xem Statistics Quizcard</button></section></main>
}
